service: qa-events

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  role: arn:aws:iam::554407330061:role/lambda_basic_vpc_execution

functions:
  simpleSuccess:
    handler: nodejs/handler.simpleSuccess
    events:
      - schedule: rate(1 minute)
  simpleSuccessStaging:
    handler: nodejs/handler.simpleSuccessStaging
    events:
      - schedule: rate(1 minute)
  node43SimpleSuccess:
    handler: nodejs/handler.simpleSuccess
    runtime: nodejs4.3
    events:
      - schedule: rate(5 minutes)
  simpleFailure:
    handler: nodejs/handler.simpleFailure
    events:
      - schedule: rate(1 minute)
  randomSuccessError:
    handler: nodejs/handler.randomSuccessError
    events:
      - schedule: rate(2 minutes)
  longRunningSuccess:
    handler: nodejs/handler.longRunningSuccess
    events:
      - schedule: rate(5 minutes)
  customEvents:
    handler: nodejs/handler.customEvents
    events:
      - schedule: rate(1 minute)
  thrownFailure:
    handler: nodejs/handler.thrownFailure
    events:
      - schedule: rate(5 minutes)
  pySimpleSuccess:
    handler: python/main.simpleSuccess
    runtime: python2.7
    events:
      - schedule: rate(1 minute)
  pyForcedFailure:
    handler: python/main.forcedFailure
    runtime: python2.7
    events:
      - schedule: rate(1 minute)
  pyLongRunning:
    handler: python/main.longRunning
    runtime: python2.7
    events:
      - schedule: rate(5 minutes)
  py3SimpleSuccess:
    handler: python/main.simpleSuccess
    runtime: python3.6
    events:
      - schedule: rate(1 minute)
  py3ForcedFailure:
    handler: python/main.forcedFailure
    runtime: python3.6
    events:
      - schedule: rate(1 minute)
  py3LongRunning:
    handler: python/main.longRunning
    runtime: python3.6
    events:
      - schedule: rate(5 minutes)

